Repository DSM-PICK/PICK2023_SERVER_SPRING, pull requests merged in 2023-02, with the labels that each got.

#24 🔀 :: (#34) 외출한 학생 리스트 조회 API
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/api/ApplicationApi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/api/dto/response/QueryPicnicStudentElement.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/api/dto/response/QueryPicnicStudentList.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/spi/QueryApplicationSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/spi/QueryStatusSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/usecase/ApplicationUseCase.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/persistence/adapter/ApplicationPersistenceAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/persistence/adapter/StatusPersistenceAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/persistence/entity/StatusEntity.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/presentation/ApplicationWebAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/teacher/presentation/TeacherWebAdapter.kt
Labels: chore, 기능 추가, 리팩토링

#25 🔀 :: (#36) 외출신청 거절 API
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/api/ApplicationApi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/usecase/ApplicationUseCase.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/persistence/entity/StatusEntity.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/presentation/ApplicationWebAdapter.kt
Labels: chore, 기능 추가, 리팩토링

#23 🔀 :: (#30) 오늘의 자습감독선생님
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/DependencyVersions.kt
  buildSrc/src/main/kotlin/PluginVersions.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/common/error/ErrorProperty.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/common/error/PickException.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/Application.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/Status.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/spi/UserQueryApplicationSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/Classroom.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/ClassroomMovement.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/api/ClassroomMovementApi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/api/dto/response/ClassroomElement.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/spi/ClassroomSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/spi/CommandClassroomMovementSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/spi/QueryClassroomSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/club/Club.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/SelfStudyDirector.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/api/SelfStudyDirectorApi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/api/dto/response/TodaySelfStudyTeacherResponse.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/spi/UserQuerySelfStudyDirectorSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/usecase/SelfStudyDirectorUseCase.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/teacher/api/dto/request/DomainUpdateStudentStatusRequest.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/teacher/spi/UserQueryTeacherSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/user/User.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/user/dto/UserInfo.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/user/spi/UserSpi.kt
  pick-infrastructure/build.gradle.kts
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/PickServerSpringApplication.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/common/feign/client/UserClient.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/common/feign/client/dto/response/TimeResponse.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/common/feign/client/dto/response/UserInfoResponse.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/common/uuid/CustomUUIDGenerator.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/persistence/entity/ApplicationEntity.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/presentation/ApplicationWebAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/persistence/adapter/ClassPersistenceAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/persistence/entity/ClassroomMovementEntity.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/persistence/SelfStudyDirectorPersistenceAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/persistence/entity/SelfStudyDirectorEntity.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/presentation/SelfStudyDirectorWebAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/teacher/presentation/dto/request/UpdateStudentStatusRequest.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/user/persistence/UserPersistenceAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/global/entity/BaseUUIDEntity.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/global/error/GlobalErrorCode.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/global/error/GlobalErrorHandler.kt
Labels: 기능 추가

#26 🔀 :: (#35) 메인페이지 학생 상태 수 (외출, 이동, 외출신청)
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/spi/QueryStatusSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/api/ClassroomMovementApi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/api/dto/request/DomainClassroomMovementRequest.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/spi/ClassroomMovementSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/spi/QueryClassroomMovementSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/usecase/ClassroomMovementUseCase.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/teacher/api/TeacherApi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/teacher/api/dto/response/QueryStudentStatusCountResponse.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/teacher/spi/StatusCommandTeacherSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/teacher/usecase/TeacherUseCase.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/persistence/adapter/StatusPersistenceAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/presentation/ApplicationWebAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/persistence/adapter/ClassroomMovementPersistenceAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/presentation/dto/request/ClassroomMovementRequest.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/teacher/presentation/TeacherWebAdapter.kt
Labels: 기능 추가

#27 🔀 :: (#38) 교실이동 API 에러 수정
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/usecase/ClassroomMovementUseCase.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/presentation/ApplicationWebAdapter.kt
Labels: 버그, 리팩토링

#29 🔀 :: (#40) 엔티티들 ERD 변경 사항대로 수정
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/Application.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/StatusType.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/api/ApplicationApi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/api/dto/request/DomainApplicationGoOutRequest.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/api/dto/request/DomainApplicationUserIdsRequest.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/spi/CommandApplicationSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/spi/QueryStatusSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/usecase/ApplicationUseCase.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/Classroom.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/ClassroomMovement.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/spi/CommandClassroomMovementSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/usecase/ClassroomMovementUseCase.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/club/Club.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/teacher/spi/StatusCommandTeacherSpi.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/mapper/ApplicationMapperImpl.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/persistence/adapter/ApplicationPersistenceAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/persistence/adapter/StatusPersistenceAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/persistence/entity/ApplicationEntity.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/presentation/ApplicationWebAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/presentation/dto/request/ApplicationGoOutRequest.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/presentation/dto/request/ApplicationUserIdsRequest.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/mapper/ClassroomMapperImpl.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/mapper/ClassroomMovementMapperImpl.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/persistence/adapter/ClassroomMovementPersistenceAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/persistence/entity/ClassroomEntity.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/persistence/entity/ClassroomMovementEntity.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/club/mapper/ClubEntityMapperImpl.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/club/persistence/entity/ClubEntity.kt
Labels: chore, 리팩토링

#32 🔀 :: (#43) 반 별 유저 목록 조회 feign 세팅
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/teacher/spi/UserQueryTeacherSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/user/dto/UserInfo.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/common/feign/client/UserClient.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/common/feign/client/dto/response/UserInfoResponse.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/common/feign/client/dto/response/UserResponse.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/user/persistence/UserPersistenceAdapter.kt
Labels: 기능 추가, 리팩토링

#30 🔀 :: (#39) 담당 층별 교실 리스트 API
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/api/ClassroomApi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/error/ClassroomErrorCode.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/exception/FloorNotFoundException.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/spi/QueryClassroomSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/usecase/ClassroomUseCase.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/spi/QuerySelfStudyDirectorSpi.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/persistence/adapter/ClassPersistenceAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/persistence/SelfStudyDirectorPersistenceAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/teacher/presentation/TeacherWebAdapter.kt
Labels: 기능 추가

#36 🔀 :: (#48) 방과후 - 인원 삭제
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/afterschool/api/.gitkeep
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/afterschool/api/AfterSchoolApi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/afterschool/api/dto/DomainDeleteAfterSchoolStudentRequest.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/afterschool/error/.gitkeep
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/afterschool/error/AfterSchoolErrorCode.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/afterschool/exception/.gitkeep
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/afterschool/exception/AfterSchoolNotFoundException.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/afterschool/exception/AfterSchoolStudentNotFoundException.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/afterschool/spi/.gitkeep
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/afterschool/spi/AfterSchoolSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/afterschool/spi/CommandAfterSchoolSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/afterschool/spi/QueryAfterSchoolSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/afterschool/usecase/.gitkeep
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/afterschool/usecase/AfterSchoolUseCase.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/afterschool/mapper/AfterSchoolMapper.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/afterschool/mapper/AfterSchoolMapperImpl.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/afterschool/persistence/adpater/AfterSchoolPersistenceAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/afterschool/presentation/.gitkeep
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/afterschool/presentation/AfterSchoolWebAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/afterschool/presentation/dto/requset/DeleteAfterSchoolStudentRequest.kt
Labels: 기능 추가

#35 🔀 :: (#46) 층별 교실 리스트 API 명세대로 수정
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/afterschool/error/AfterSchoolErrorCode.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/afterschool/spi/QueryAfterSchoolSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/ClassroomType.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/api/ClassroomApi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/api/dto/response/ClassroomElement.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/spi/QueryClassroomSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/usecase/ClassroomMovementUseCase.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/usecase/ClassroomUseCase.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/club/error/.gitkeep
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/club/error/ClubErrorCode.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/club/exception/.gitkeep
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/club/exception/ClubNotFoundException.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/club/spi/.gitkeep
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/club/spi/ClubSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/club/spi/CommandClubSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/club/spi/QueryClubSpi.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/afterschool/persistence/adapter/AfterSchoolPersistenceAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/persistence/adapter/ClassPersistenceAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/presentation/ClassroomWebAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/club/mapper/ClubMapper.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/club/mapper/ClubMapperImpl.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/club/persistence/adapter/ClubPersistenceAdapter.kt
Labels: chore, 기능 추가, 리팩토링

#37 🔀 :: (#49) 담당 층별 교실 리스트 조회 API 명세대로 수정
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/afterschool/spi/QueryAfterSchoolSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/afterschool/vo/AfterSchoolRoomVO.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/spi/QueryClassroomSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/usecase/ClassroomUseCase.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/vo/ClassroomVO.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/club/spi/QueryClubSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/club/vo/ClubRoomVO.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/spi/QueryTypeSpi.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/afterschool/persistence/adapter/AfterSchoolPersistenceAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/afterschool/persistence/vo/QueryAfterSchoolRoomVO.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/persistence/adapter/ClassPersistenceAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/persistence/vo/QueryClassroomVO.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/club/persistence/adapter/ClubPersistenceAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/club/persistence/vo/QueryClubRoomVO.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/persistence/adapter/TypePersistenceAdapter.kt
Labels: chore, 기능 추가, 리팩토링

#40 🔀 :: (#52) 외출복귀 API
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/Status.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/spi/QueryStatusSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/usecase/ApplicationUseCase.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/teacher/api/TeacherApi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/teacher/api/dto/request/DomainComebackStudentRequest.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/teacher/usecase/TeacherUseCase.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/persistence/adapter/StatusPersistenceAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/teacher/presentation/TeacherWebAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/teacher/presentation/dto/request/ComebackStudentRequest.kt
Labels: 기능 추가, 리팩토링

#41 🔀 :: (#57) 외출증 발급 API
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/api/ApplicationApi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/api/dto/request/DomainPicnicPassRequest.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/usecase/ApplicationUseCase.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/admin/presentation/AdminWebAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/admin/presentation/dto/request/PicnicPassRequest.kt
Labels: 기능 추가

#42 🔀 :: (#55) 자습감독 여부 API
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/api/SelfStudyDirectorApi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/api/dto/response/SelfStudyStateResponse.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/error/SelfStudyDirectorErrorCode.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/exception/SelfStudyDirectorNotFoundException.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/spi/QuerySelfStudyDirectorSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/usecase/SelfStudyDirectorUseCase.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/admin/presentation/AdminWebAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/persistence/adapter/SelfStudyDirectorPersistenceAdapter.kt
Labels: 기능 추가

#43 🔀 :: (#60) Cors 설정
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/global/security/WebConfig.kt
Labels: 프로젝트 세팅

#44 🔀 :: (#59) 자습감독선생님 변경
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/afterschool/AfterSchool.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/Application.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/Status.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/Classroom.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/ClassroomMovement.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/club/Club.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/SelfStudyDirector.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/Type.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/api/SelfStudyDirectorApi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/api/dto/requst/DomainChangeSelfStudyDirectorRequest.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/spi/CommandSelfStudyDirectorSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/spi/QuerySelfStudyDirectorSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/spi/SelfStudyDirectorSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/usecase/SelfStudyDirectorUseCase.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/user/User.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/admin/presentation/AdminWebAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/admin/presentation/dto/request/ChangeSelfStudyDirectorRequset.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/persistence/adapter/SelfStudyDirectorPersistenceAdapter.kt
Labels: 기능 추가

#45 🔀 :: (#56) 반 별 학생 상태 변경 API
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/admin/api/AdminApi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/admin/api/dto/request/DomainUpdateStudentStatusOfClassRequest.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/admin/usecase/AdminUseCase.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/Status.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/StatusType.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/error/StatusErrorCode.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/exception/CannotChangeEmploymentException.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/exception/CannotChangeStatusThisTimeException.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/spi/QueryStatusSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/usecase/ApplicationUseCase.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/time/spi/QueryTimeSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/time/spi/TimeSpi.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/admin/presentation/AdminWebAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/admin/presentation/dto/request/UpdateStudentStatusOfClassRequest.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/persistence/StatusRepository.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/persistence/adapter/StatusPersistenceAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/persistence/entity/StatusEntity.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/time/TimePersistenceAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/global/config/SchedulerConfig.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/global/scheduler/StatusScheduler.kt
Labels: chore, 기능 추가, 리팩토링

#46 🔀 :: (#58) 학생 동아리 변경 API
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/club/Club.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/club/api/ClubApi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/club/api/dto/DomainChangeClubStudentRequest.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/club/usecase/ClubUseCase.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/admin/presentation/AdminWebAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/admin/presentation/dto/request/ChangeClubStudentRequest.kt
Labels: 기능 추가

#48 🔀 :: (#53) 외출 거절, 수락 API
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/Status.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/api/ApplicationApi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/api/dto/request/DomainPicnicAcceptOrRefuseRequest.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/usecase/ApplicationUseCase.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/teacher/presentation/TeacherWebAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/teacher/presentation/dto/request/PicnicAcceptOrRefuseRequest.kt
Labels: 기능 추가

#50 🔀 :: (#64) 날짜로 타입 조회 API
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/admin/api/AdminApi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/admin/api/dto/response/QueryTypeResponse.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/admin/usecase/AdminUseCase.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/api/SelfStudyDirectorApi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/spi/QueryTypeSpi.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/admin/presentation/AdminWebAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/persistence/adapter/TypePersistenceAdapter.kt
Labels: 기능 추가

#47 🔀 :: (#47) 외출 신청 리스트 층 별 필터링 추가
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/afterschool/spi/QueryAfterSchoolSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/api/ApplicationApi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/usecase/ApplicationUseCase.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/spi/QueryClassroomSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/club/spi/QueryClubSpi.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/afterschool/persistence/adapter/AfterSchoolPersistenceAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/persistence/adapter/ClassPersistenceAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/club/persistence/adapter/ClubPersistenceAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/teacher/presentation/TeacherWebAdapter.kt
Labels: 기능 추가

#51 🔀 :: (#63) 출석 확인 리스트 조회 API
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/admin/api/AdminApi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/admin/api/dto/response/QueryStudentAttendanceList.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/admin/usecase/AdminUseCase.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/afterschool/api/AfterSchoolApi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/afterschool/api/dto/request/DomainCreateAfterSchoolStudentRequest.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/afterschool/api/dto/request/DomainDeleteAfterSchoolStudentRequest.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/afterschool/spi/QueryAfterSchoolSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/afterschool/usecase/AfterSchoolUseCase.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/api/ApplicationApi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/api/dto/request/DomainPicnicPassRequest.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/api/dto/response/QueryStudentStatusElement.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/spi/QueryStatusSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/club/spi/QueryClubSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/spi/QueryTypeSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/teacher/spi/UserQueryTeacherSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/time/Time.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/common/feign/client/UserClient.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/common/feign/client/dto/response/TimeResponse.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/admin/presentation/AdminWebAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/afterschool/persistence/adapter/AfterSchoolPersistenceAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/persistence/adapter/StatusPersistenceAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/club/persistence/adapter/ClubPersistenceAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/persistence/adapter/TypePersistenceAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/time/TimePersistenceAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/user/persistence/UserPersistenceAdapter.kt
Labels: 기능 추가, 리팩토링

#49 🔀 :: (#62) 이동 제한 api
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/spi/CommandStatusSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/api/SelfStudyDirectorApi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/spi/CommandSelfStudyDirectorSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/spi/QuerySelfStudyDirectorSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/spi/SelfStudyDirectorSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/usecase/SelfStudyDirectorUseCase.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/admin/presentation/AdminWebAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/persistence/adapter/StatusPersistenceAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/persistence/SelfStudyDirectorRepository.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/persistence/adapter/SelfStudyDirectorPersistenceAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/persistence/entity/SelfStudyDirectorEntity.kt
Labels: 기능 추가
