Repository DSM-PICK/PICK2023_SERVER_SPRING, pull requests merged in 2023-01, with the labels that each got.

#2 🔀 :: (#1) 프로젝트 세팅 & 아키텍처링
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/todo.yml
  .github/workflows/CI.yml
  .gitignore
  build.gradle.kts
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  pick-application/build.gradle.kts
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/common/annotation/Aggregate.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/common/annotation/ReadOnlyUseCase.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/common/annotation/UseCase.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/common/error/.gitkeep
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/api/.gitkeep
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/error/.gitkeep
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/exception/.gitkeep
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/spi/.gitkeep
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/usecase/.gitkeep
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/class_room/api/.gitkeep
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/class_room/error/.gitkeep
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/class_room/exception/.gitkeep
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/class_room/spi/.gitkeep
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/class_room/usecase/.gitkeep
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/club/api/.gitkeep
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/club/error/.gitkeep
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/club/exception/.gitkeep
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/club/spi/.gitkeep
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/club/usecase/.gitkeep
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/self_study_director/api/.gitkeep
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/self_study_director/error/.gitkeep
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/self_study_director/exception/.gitkeep
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/self_study_director/spi/.gitkeep
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/self_study_director/usecase/.gitkeep
  pick-infrastructure/build.gradle.kts
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/PickServerSpringApplication.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/mapper/.gitkeep
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/persistence/entity/.gitkeep
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/presentation/.gitkeep
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/class_room/mapper/.gitkeep
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/class_room/persistence/entity/.gitkeep
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/class_room/presentation/.gitkeep
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/club/mapper/.gitkeep
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/club/persistence/entity/.gitkeep
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/club/presentation/.gitkeep
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/self_study_director/mapper/.gitkeep
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/self_study_director/persistence/entity/.gitkeep
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/self_study_director/presentation/.gitkeep
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/global/annotation/Adapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/global/annotation/config/AnnotationConfig.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/global/error/.gitkeep
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/global/exception/.gitkeep
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/global/security/.gitkeep
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/infrastructure/.gitkeep
  pick-infrastructure/src/main/resources/application.yml
  settings.gradle.kts
Labels: 프로젝트 세팅

#3 🔀 :: (#BACK-10) error Handling
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/common/error/.gitkeep
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/common/error/ErrorProperty.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/common/error/PickException.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/api/.gitkeep
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/error/.gitkeep
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/exception/.gitkeep
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/spi/.gitkeep
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/usecase/.gitkeep
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/mapper/.gitkeep
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/persistence/entity/.gitkeep
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/presentation/.gitkeep
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/global/annotation/config/AnnotationConfig.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/global/error/.gitkeep
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/global/error/ErrorResponse.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/global/error/GlobalErrorCode.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/global/error/GlobalErrorHandler.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/global/exception/.gitkeep
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/global/exception/InternalServerErrorException.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/global/filter/ExceptionFilter.kt
Labels: 프로젝트 세팅

#5 🔀 :: (#16) 자잘한 변경점 변경
  .editorconfig
  .github/CODEOWNERS
  .github/workflows/CI.yml
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/DependencyVersions.kt
  buildSrc/src/main/kotlin/PluginVersions.kt
  pick-application/build.gradle.kts
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/common/annotation/Aggregate.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/common/annotation/ReadOnlyUseCase.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/common/annotation/UseCase.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/common/error/ErrorProperty.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/common/error/PickException.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/api/.gitkeep
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/error/.gitkeep
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/exception/.gitkeep
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/spi/.gitkeep
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/usecase/.gitkeep
  pick-infrastructure/build.gradle.kts
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/mapper/.gitkeep
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/persistence/entity/.gitkeep
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/presentation/.gitkeep
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/global/annotation/config/AnnotationConfig.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/global/error/ErrorResponse.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/global/error/GlobalErrorCode.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/global/error/GlobalErrorHandler.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/global/exception/InternalServerErrorException.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/global/filter/ExceptionFilter.kt
Labels: chore, 기능 추가, 리팩토링

#4 🔀 :: (#BACK-12) 자습감독선생님 빼고 모든 엔티티 생성
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/Application.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/Status.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/error/.gitkeep
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/error/StatusErrorCode.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/exception/.gitkeep
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/exception/StatusNotFoundException.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/Classroom.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/ClassroomMovement.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/error/.gitkeep
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/error/ClassroomErrorCode.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/exception/.gitkeep
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/exception/ClassroomNotFoundException.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/club/Club.kt
  pick-infrastructure/build.gradle.kts
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/mapper/.gitkeep
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/mapper/ApplicationMapper.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/mapper/ApplicationMapperImpl.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/mapper/StatusMapper.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/mapper/StatusMapperImpl.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/persistence/ApplicationRepository.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/persistence/StatusRepository.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/persistence/entity/.gitkeep
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/persistence/entity/ApplicationEntity.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/persistence/entity/StatusEntity.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/mapper/.gitkeep
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/mapper/ClassroomMapper.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/mapper/ClassroomMapperImpl.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/mapper/ClassroomMovementMapper.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/mapper/ClassroomMovementMapperImpl.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/persistence/ClassroomMovementRepository.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/persistence/ClassroomRepository.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/persistence/entity/.gitkeep
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/persistence/entity/ClassroomEntity.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/persistence/entity/ClassroomMovementEntity.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/club/mapper/.gitkeep
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/club/mapper/ClubEntityMapper.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/club/mapper/ClubEntityMapperImpl.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/club/persistence/ClubRepository.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/club/persistence/entity/.gitkeep
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/club/persistence/entity/ClubEntity.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/global/entity/BaseUUIDEntity.kt
  pick-infrastructure/src/main/resources/application.yml
Labels: 프로젝트 세팅

#7 🔀 :: (#9) Security 기본 설정 및 의존성 수정
  buildSrc/src/main/kotlin/DependencyVersions.kt
  pick-infrastructure/build.gradle.kts
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/global/security/.gitkeep
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/global/security/AuthenticationFilter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/global/security/FilterConfig.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/global/security/SecurityConfig.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/global/security/UserRole.kt
  pick-infrastructure/src/main/resources/application.yml
Labels: chore, 프로젝트 세팅

#8 🔀 :: (#12) Status테이블 type컬럼 Enum타입으로 변경
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/Status.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/StatusType.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/persistence/entity/StatusEntity.kt
Labels: 프로젝트 세팅

#6 🔀 :: (#15) 자습감독선생님 Entity 생성
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/DirectorType.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/SelfStudyDirector.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/mapper/.gitkeep
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/mapper/SelfStudyDirectorMapper.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/mapper/SelfStudyDirectorMapperImpl.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/persistence/SelfStudyDirectorRepository.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/persistence/entity/.gitkeep
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/persistence/entity/SelfStudyDirectorEntity.kt
Labels: 프로젝트 세팅

#9 🔀 :: (#17) OpenFeign 기본설정 & User Feign 설정
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/common/feign/FeignClientErrorDecoder.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/common/feign/FeignConfig.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/common/feign/client/UserClient.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/common/feign/client/dto/response/UserInfoElement.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/common/feign/client/dto/response/UserInfoResponse.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/common/feign/error/FeignErrorCode.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/common/feign/exception/FeignBadRequestException.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/common/feign/exception/FeignExpiredTokenException.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/common/feign/exception/FeignForbiddenException.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/common/feign/exception/FeignInternalServerError.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/common/feign/exception/FeignUnAuthorizedException.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/infrastructure/.gitkeep
Labels: chore, 프로젝트 세팅

#11 🔀 :: (#21) 엔티티 수정
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/Application.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/mapper/ApplicationMapperImpl.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/persistence/entity/ApplicationEntity.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/mapper/ClassroomMovementMapperImpl.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/persistence/entity/ClassroomMovementEntity.kt
Labels: 버그

#12 🔀 :: (#18) 교실이동 API
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/api/.gitkeep
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/api/ClassroomMovementApi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/spi/.gitkeep
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/spi/ClassroomMovementSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/spi/ClassroomSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/spi/CommandClassroomMovementSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/spi/QueryClassroomSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/usecase/.gitkeep
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/usecase/ClassroomMovementUseCase.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/user/spi/UserSpi.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/presentation/.gitkeep
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/presentation/ApplicationWebAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/persistence/ClassroomRepository.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/persistence/adapter/ClassPersistenceAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/persistence/adapter/ClassroomMovementPersistenceAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/presentation/.gitkeep
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/user/persistence/UserPersistenceAdapter.kt
Labels: 기능 추가

#13 🔀 :: (#22) CD 세팅
  .github/workflows/CD.yml
  Dockerfile
Labels: 프로젝트 세팅

#15 🔀 :: (#23) UUID 생성 방식 수정
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/Application.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/Status.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/Classroom.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/ClassroomMovement.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/club/Club.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/SelfStudyDirector.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/common/uuid/CustomUUIDGenerator.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/persistence/entity/ApplicationEntity.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/persistence/entity/SelfStudyDirectorEntity.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/global/entity/BaseUUIDEntity.kt
Labels: 리팩토링

#16 🔀 :: (#24) 외출 신청 API
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/api/.gitkeep
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/api/ApplicationApi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/api/dto/request/DomainApplicationGoOutRequest.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/spi/.gitkeep
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/spi/ApplicationSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/spi/CommandApplicationSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/usecase/.gitkeep
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/usecase/ApplicationUseCase.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/persistence/adapter/ApplicationPersistenceAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/presentation/ApplicationWebAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/presentation/dto/request/ApplicationGoOutRequest.kt
Labels: 기능 추가

#14 🔀 :: (#19) 외출신청 조회 API
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/api/ApplicationApi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/api/dto/response/QueryPicnicApplicationElement.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/api/dto/response/QueryPicnicApplicationList.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/spi/ApplicationSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/spi/QueryApplicationSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/usecase/ApplicationUseCase.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/user/User.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/user/dto/UserInfo.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/user/spi/ApplicationUserSpi.kt
  pick-infrastructure/build.gradle.kts
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/common/feign/client/UserClient.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/common/feign/client/dto/response/UserInfoElement.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/common/feign/client/dto/response/UserInfoResponse.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/persistence/ApplicationRepository.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/persistence/adapter/ApplicationPersistenceAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/presentation/ApplicationWebAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/user/persistence/UserPersistenceAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/global/querydsl/QuerydslConfig.kt
Labels: 기능 추가

#18 🔀 :: (#28) 자습감독 선생님 리스트 API
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/spi/UserQueryApplicationSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/usecase/ApplicationUseCase.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/api/.gitkeep
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/api/SelfStudyDirectorApi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/api/dto/response/SelfStudyElement.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/api/dto/response/SelfStudyListResponse.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/spi/.gitkeep
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/spi/QuerySelfStudyDirectorSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/spi/SelfStudyDirectorSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/spi/UserQuerySelfStudyDirectorSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/usecase/.gitkeep
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/usecase/SelfStudyDirectorUseCase.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/user/spi/ApplicationUserSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/user/spi/UserSpi.kt
  pick-infrastructure/build.gradle.kts
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/common/feign/client/UserClient.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/common/feign/client/dto/response/UserInfoElement.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/common/feign/client/dto/response/UserInfoResponse.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/mapper/SelfStudyDirectorMapperImpl.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/persistence/SelfStudyDirectorPersistenceAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/presentation/.gitkeep
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/presentation/SelfStudyDirectorWebAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/user/persistence/UserPersistenceAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/global/annotation/NoArg.kt
Labels: chore, 기능 추가, 리팩토링

#17 🔀 :: (#20) 층별 교실 리스트 API
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/api/ClassroomApi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/api/dto/response/ClassroomElement.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/api/dto/response/QueryClassroomList.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/spi/ClassroomSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/spi/QueryClassroomSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/usecase/ClassroomUseCase.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/persistence/ClassroomRepository.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/persistence/adapter/ClassPersistenceAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/presentation/ClassroomWebAdapter.kt
Labels: 기능 추가

#19 🔀 :: (#29) 학생 출결 상태 변경 API
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/Status.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/spi/StatusSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/teacher/api/TeacherApi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/teacher/api/dto/request/DomainUpdateStudentStatusRequest.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/teacher/spi/StatusCommandTeacherSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/teacher/spi/TimeQueryTeacherSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/teacher/spi/UserQueryTeacherSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/teacher/usecase/TeacherUseCase.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/time/Time.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/time/error/TimeErrorCode.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/time/exception/TimeNotFoundException.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/time/spi/TimeSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/user/error/UserErrorCode.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/user/exception/UserNotFoundException.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/user/spi/UserSpi.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/common/feign/client/TimeClient.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/common/feign/client/dto/response/TimeResponse.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/common/feign/client/dto/response/UserInfoElement.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/common/feign/client/dto/response/UserInfoResponse.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/mapper/StatusMapperImpl.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/persistence/adapter/StatusPersistenceAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/persistence/entity/StatusEntity.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/teacher/presentation/TeacherWebAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/teacher/presentation/dto/request/UpdateStudentStatusRequest.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/time/TimeFeignAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/user/persistence/UserPersistenceAdapter.kt
Labels: chore, 기능 추가, 리팩토링
