Repository DSM-PICK/PICK2023_SERVER_SPRING, pull requests merged in 2023-05, with the labels that each got.

#93 🔀 :: (#18) feign 요청 에러 코드 수정
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/admin/usecase/AdminUseCase.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/afterschool/usecase/AfterSchoolUseCase.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/spi/UserQueryApplicationSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/usecase/ApplicationUseCase.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/usecase/ClassroomMovementUseCase.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/spi/UserQuerySelfStudyDirectorSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/usecase/SelfStudyDirectorUseCase.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/teacher/spi/UserQueryTeacherSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/teacher/usecase/TeacherUseCase.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/user/dto/request/UserInfoRequest.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/common/feign/client/UserClient.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/user/persistence/UserPersistenceAdapter.kt
Labels: 버그

#95 🔀 :: (#25) 담당 층별 교실 리스트 에러 코드 수정
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/usecase/ClassroomUseCase.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/spi/QuerySelfStudyDirectorSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/spi/QueryTypeSpi.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/persistence/adapter/SelfStudyDirectorPersistenceAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/persistence/adapter/TypePersistenceAdapter.kt
Labels: 버그, chore

#96 🔀 :: (#70) 외출증 확인 404 오류
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/spi/QueryStatusSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/usecase/ApplicationUseCase.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/spi/UserQuerySelfStudyDirectorSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/teacher/spi/UserQueryTeacherSpi.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/admin/presentation/dto/request/DeleteSelfStudyDirectorRequest.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/persistence/adapter/StatusPersistenceAdapter.kt
Labels: 버그

#98 🔀 :: (#86) 외출증 확인 Response에 외출 날짜 추가
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/api/dto/response/QueryMyPicnicInfoResponse.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/usecase/ApplicationUseCase.kt
Labels: chore

#97 🔀 :: (#87) 교실이동 에러 핸들링 잘못된 조건 수정
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/afterschool/spi/QueryAfterSchoolSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/afterschool/usecase/AfterSchoolUseCase.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/ClassroomMovement.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/spi/QueryClassroomMovementSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/usecase/ClassroomMovementUseCase.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/club/spi/QueryClubSpi.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/afterschool/persistence/adapter/AfterSchoolPersistenceAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/persistence/ClassroomRepository.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/persistence/adapter/ClassPersistenceAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/persistence/adapter/ClassroomMovementPersistenceAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/club/persistence/adapter/ClubPersistenceAdapter.kt
Labels: chore, 리팩토링

#100 🔀 :: (#96) 방과후일 때는 같은 교실이동에 관한 처리 안 하도록 수정
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/usecase/ClassroomMovementUseCase.kt
Labels: chore

#102 🔀 :: (#102) 현재 나의 교실 위치 조회 API 오류 수정
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/spi/QueryStatusSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/spi/QueryClassroomMovementSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/spi/QueryClassroomSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/usecase/ClassroomMovementUseCase.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/persistence/adapter/StatusPersistenceAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/persistence/adapter/ClassPersistenceAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/persistence/adapter/ClassroomMovementPersistenceAdapter.kt
Labels: 버그, chore, 리팩토링

#104 🔀 :: (#52) 교실 이동 복귀 리팩토링
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/spi/QueryStatusSpi.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/persistence/adapter/StatusPersistenceAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/persistence/adapter/ClassroomMovementPersistenceAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/persistence/adapter/SelfStudyDirectorPersistenceAdapter.kt
Labels: 버그, chore

#106 🔀 :: (#109) 학번 0 붙이는 처리 메소드 리팩토링
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/admin/usecase/AdminUseCase.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/afterschool/usecase/AfterSchoolUseCase.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/spi/QueryApplicationSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/spi/QueryStatusSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/usecase/ApplicationUseCase.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/usecase/ClassroomMovementUseCase.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/teacher/usecase/TeacherUseCase.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/persistence/adapter/ApplicationPersistenceAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/persistence/adapter/StatusPersistenceAdapter.kt
Labels: chore, 리팩토링

#107 🔀 :: (#117) 쿼리 잘못된 부분 수정
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/spi/QueryStatusSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/teacher/usecase/TeacherUseCase.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/persistence/adapter/StatusPersistenceAdapter.kt
Labels: chore
