Repository DSM-PICK/PICK2023_SERVER_SPRING, pull requests merged in 2023-04, with the labels that each got.

#80 🔀 :: (#85) 메인페이지 학생 상태 수 조회 API 수정
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/spi/QueryStatusSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/teacher/usecase/TeacherUseCase.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/persistence/adapter/StatusPersistenceAdapter.kt
Labels: chore, 리팩토링

#82 🔀 :: (#81) 자습감독 선생님 일괄변경 버그 수정
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/spi/CommandSelfStudyDirectorSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/usecase/SelfStudyDirectorUseCase.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/persistence/adapter/SelfStudyDirectorPersistenceAdapter.kt
Labels: 버그

#83 🔀 :: (#26) 정렬 코드 추가
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/admin/usecase/AdminUseCase.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/usecase/ClassroomMovementUseCase.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/usecase/ClassroomUseCase.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/teacher/usecase/TeacherUseCase.kt
Labels: chore

#87 🔀 :: (#22) 외출증 조회 오늘것만 가져오도록 수정
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/spi/QueryStatusSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/usecase/ApplicationUseCase.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/persistence/adapter/StatusPersistenceAdapter.kt
Labels: chore, 리팩토링

#89 🔀 :: (#9) 자습감독 선생님 삭제 API 구현
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/api/SelfStudyDirectorApi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/api/dto/request/DomainDeleteSelfStudyDirectorRequest.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/spi/CommandSelfStudyDirectorSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/usecase/SelfStudyDirectorUseCase.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/admin/presentation/AdminWebAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/admin/presentation/dto/request/DeleteSelfStudyDirectorRequest.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/persistence/adapter/SelfStudyDirectorPersistenceAdapter.kt
Labels: 기능 추가

#88 🔀 :: (#10) 외출 신청 중복 방지 && 주말에 외출 신청 못하도록 수정
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/error/ApplicationErrorCode.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/exception/AlreadyApplicationPicnicOrAlreadyPicnicException.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/exception/CannotApplicationWeekendException.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/spi/QueryStatusSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/usecase/ApplicationUseCase.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/persistence/adapter/StatusPersistenceAdapter.kt
Labels: chore, 리팩토링

#90 🔀 :: (#11) 주말 교실 이동 제한
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/error/ClassroomErrorCode.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/exception/CannotMovementWeekendException.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/usecase/ClassroomMovementUseCase.kt
Labels: chore

#91 🔀 :: (#16) UserFeign Http 4096 bytes 에러 해결
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/common/feign/client/UserClient.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/user/persistence/UserPersistenceAdapter.kt
Labels: 버그

#92 🔀 :: (#17) Enum 추가에 따른 코드 변경
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/ClassroomType.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/usecase/ClassroomUseCase.kt
Labels: 버그
