Repository DSM-PICK/PICK2023_SERVER_SPRING, pull requests merged in 2023-06, with the labels that each got.

#108 🔀 :: (#120) AdminUseCase 부분 리팩토링
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/admin/usecase/AdminUseCase.kt
Labels: chore, 리팩토링

#110 🔀 :: (#85) Sentry 세팅
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/DependencyVersions.kt
  pick-infrastructure/build.gradle.kts
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/global/filter/ExceptionFilter.kt
  pick-infrastructure/src/main/resources/application.yml
Labels: chore, 기능 추가

#111 🔀 :: (#42) 학생 복귀시 출석으로 변경되지 않도록 수정
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/Status.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/teacher/usecase/TeacherUseCase.kt
Labels: chore

#109 🔀 :: (#81) 외출증 복귀 시간 지나면 뜨지 않도록 변경
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/error/StatusErrorCode.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/exception/OverEndTimeException.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/usecase/ApplicationUseCase.kt
Labels: chore

#113 🔀 :: (#114) 어드민 학생 상태 수 조회 API 버그 수정
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/spi/QuerySelfStudyDirectorSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/teacher/usecase/TeacherUseCase.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/persistence/adapter/SelfStudyDirectorPersistenceAdapter.kt
Labels: 버그, chore

#112 🔀 :: (#113) Sentry CaptureException 위치 변경 && IllegalArgumentException 핸들링
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/global/error/ErrorResponse.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/global/error/GlobalErrorHandler.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/global/filter/ExceptionFilter.kt
Labels: chore

#115 🔀 :: (#154) 허용 도메인 추가
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/global/security/WebConfig.kt
Labels: chore

#116 🔀 :: (#155) 학생 복귀 여부 칼럼 추가
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/Application.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/usecase/ApplicationUseCase.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/teacher/usecase/TeacherUseCase.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/mapper/ApplicationMapperImpl.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/persistence/adapter/StatusPersistenceAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/persistence/entity/ApplicationEntity.kt
Labels: chore
