Repository DSM-PICK/PICK2023_SERVER_SPRING, pull requests merged in 2023-03, with the labels that each got.

#52 🔀 :: (#65) 학생 출결 상태 변경 API 명세 바뀐대로 수정
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/usecase/ApplicationUseCase.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/teacher/api/dto/request/DomainUpdateStudentStatusRequest.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/teacher/usecase/TeacherUseCase.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/teacher/presentation/TeacherWebAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/teacher/presentation/dto/request/UpdateStudentStatusRequest.kt
Labels: chore, 리팩토링

#54 🔀 :: (#68) 방과후 - 인원 조회 API
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/afterschool/api/AfterSchoolApi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/afterschool/api/dto/response/QueryAfterSchoolStudentList.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/afterschool/spi/QueryAfterSchoolSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/afterschool/usecase/AfterSchoolUseCase.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/admin/presentation/AdminWebAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/afterschool/persistence/adapter/AfterSchoolPersistenceAdapter.kt
Labels: 기능 추가, 리팩토링

#55 🔀 :: (#69) 동아리 인원 조회 API
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/admin/api/dto/response/QueryClubStudentList.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/club/api/ClubApi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/club/spi/QueryClubSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/club/usecase/ClubUseCase.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/teacher/error/TeacherErrorCode.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/teacher/exception/TeacherNotFoundException.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/admin/presentation/AdminWebAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/club/persistence/adapter/ClubPersistenceAdapter.kt
Labels: 기능 추가

#57 🔀 :: (#71) 반 별 학생 상태 조회 API
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/admin/api/AdminApi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/admin/api/dto/response/QueryStudentListByGradeAndClassNum.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/admin/usecase/AdminUseCase.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/spi/QueryClassroomSpi.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/admin/presentation/AdminWebAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/persistence/adapter/ClassPersistenceAdapter.kt
Labels: 기능 추가, 리팩토링

#59 🔀 :: (#58) 상태에 자퇴 추가
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/StatusType.kt
Labels: 기능 추가

#60 🔀 :: (#72) 반 별 학생 상태 변경 API에 자퇴도 추가
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/admin/usecase/AdminUseCase.kt
Labels: chore

#61 🔀 (#73) :: 층 별 교실 리스트 api 명세대로 재수정
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/afterschool/vo/AfterSchoolRoomVO.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/api/dto/response/QueryClassroomList.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/usecase/ClassroomUseCase.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/club/vo/ClubRoomVO.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/afterschool/persistence/adapter/AfterSchoolPersistenceAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/afterschool/persistence/vo/QueryAfterSchoolRoomVO.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/club/persistence/adapter/ClubPersistenceAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/club/persistence/vo/QueryClubRoomVO.kt
Labels: chore, DOCS, 기능 추가, 리팩토링

#56 🔀 :: 이동한 학생 조회 api
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/admin/api/dto/response/QueryClubStudentList.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/afterschool/spi/QueryAfterSchoolSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/spi/QueryStatusSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/api/ClassroomMovementApi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/api/dto/response/MovementStudentElement.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/api/dto/response/QueryMovementStudentList.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/usecase/ClassroomMovementUseCase.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/club/spi/QueryClubSpi.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/admin/presentation/AdminWebAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/afterschool/persistence/AfterSchoolRepository.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/afterschool/persistence/adapter/AfterSchoolPersistenceAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/persistence/adapter/StatusPersistenceAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/club/persistence/adapter/ClubPersistenceAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/teacher/presentation/dto/request/PicnicAcceptOrRefuseRequest.kt
Labels: 기능 추가

#64 🔀 :: (#76) 나의 외출 복귀 시간 조회
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/admin/usecase/AdminUseCase.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/api/ApplicationApi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/api/dto/response/QueryMyPicnicResponse.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/spi/QueryStatusSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/usecase/ApplicationUseCase.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/spi/QueryClassroomMovementSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/spi/QueryClassroomSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/usecase/ClassroomMovementUseCase.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/club/usecase/ClubUseCase.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/persistence/adapter/StatusPersistenceAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/presentation/ApplicationWebAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/persistence/adapter/ClassPersistenceAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/persistence/adapter/ClassroomMovementPersistenceAdapter.kt
Labels: 기능 추가, 리팩토링

#65 🔀 :: (#78) User쪽 Feign 추가
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/admin/usecase/AdminUseCase.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/spi/UserQueryApplicationSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/usecase/ApplicationUseCase.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/club/usecase/ClubUseCase.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/usecase/SelfStudyDirectorUseCase.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/teacher/usecase/TeacherUseCase.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/common/feign/client/UserClient.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/user/persistence/UserPersistenceAdapter.kt
Labels: chore, 기능 추가, 리팩토링

#66 🔀 :: (#77) 현재 자신이 이동한 교실 API
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/api/ClassroomMovementApi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/api/dto/response/QueryClassroomMovementLocationResponse.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/usecase/ClassroomMovementUseCase.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/presentation/ClassroomWebAdapter.kt
Labels: 기능 추가

#67 🔀 :: (#79) 외출증 조회 API
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/api/ApplicationApi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/api/dto/response/QueryMyPicnicEndTimeResponse.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/api/dto/response/QueryMyPicnicInfoResponse.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/spi/QueryApplicationSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/usecase/ApplicationUseCase.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/persistence/adapter/ApplicationPersistenceAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/presentation/ApplicationWebAdapter.kt
Labels: 기능 추가, 리팩토링

#70 🔀 :: 이동한 학생 리스트 조회 API
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/api/ApplicationApi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/spi/QueryStatusSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/usecase/ApplicationUseCase.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/api/dto/response/ClassroomMovementStudentElement.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/api/dto/response/QueryClassroomMovementStudentList.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/usecase/ClassroomMovementUseCase.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/teacher/api/TeacherApi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/teacher/api/dto/response/QueryMovementStudentList.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/teacher/usecase/TeacherUseCase.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/persistence/adapter/StatusPersistenceAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/teacher/presentation/TeacherWebAdapter.kt
Labels: 기능 추가

#72 🔀 :: 타입 할당, 수정, 조회
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/admin/api/AdminApi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/admin/api/dto/response/QueryTypeResponse.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/admin/usecase/AdminUseCase.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/Type.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/spi/CommandTypeSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/spi/TypeSpi.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/admin/presentation/AdminWebAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/persistence/adapter/TypePersistenceAdapter.kt
Labels: 기능 추가

#71 🔀 :: (#80) 교실 이동 api 조건 검증 추가
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/spi/QueryStatusSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/error/ClassroomErrorCode.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/exception/CannotMovementException.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/usecase/ClassroomMovementUseCase.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/persistence/adapter/StatusPersistenceAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/persistence/adapter/ClassroomMovementPersistenceAdapter.kt
Labels: 기능 추가, 리팩토링

#74 🔀 :: (#83) 타입 수정 api 변경
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/admin/api/AdminApi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/admin/usecase/AdminUseCase.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/admin/presentation/AdminWebAdapter.kt
Labels: chore, 리팩토링

#76 🔀 :: (#75) 층별 자습감독 선생님 추가 API
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/api/SelfStudyDirectorApi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/api/dto/request/DomainChangeSelfStudyDirectorRequest.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/api/dto/request/DomainRegisterSelfStudyDirectorRequest.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/spi/CommandSelfStudyDirectorSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/usecase/SelfStudyDirectorUseCase.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/admin/presentation/AdminWebAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/admin/presentation/dto/request/ChangeSelfStudyDirectorRequest.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/admin/presentation/dto/request/RegisterSelfStudyDirectorRequest.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/persistence/adapter/SelfStudyDirectorPersistenceAdapter.kt
Labels: 기능 추가

#73 🔀 :: (#82) 층 이동 제한 해제 API
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/SelfStudyDirector.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/api/SelfStudyDirectorApi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/usecase/SelfStudyDirectorUseCase.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/admin/presentation/AdminWebAdapter.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/persistence/adapter/SelfStudyDirectorPersistenceAdapter.kt
Labels: 기능 추가

#78 🔀 :: (#77) 방과후 중복학생 추가 시 예외처리
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/afterschool/error/AfterSchoolErrorCode.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/afterschool/exception/AfterSchoolStudentExistsException.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/afterschool/spi/QueryAfterSchoolSpi.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/afterschool/usecase/AfterSchoolUseCase.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/afterschool/persistence/adapter/AfterSchoolPersistenceAdapter.kt
Labels: 리팩토링

#79 🔀 :: (#84) 동아리 인원 조회 500 에러 수정
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/admin/api/dto/response/QueryClubStudentList.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/club/usecase/ClubUseCase.kt
  pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/user/spi/UserSpi.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/common/feign/client/UserClient.kt
  pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/user/persistence/UserPersistenceAdapter.kt
Labels: 버그, chore
